### ISSUE TITLE
Having issues with Vagrant 2

### ISSUE THREAD

**Issue by malnick** [7Pikes/vagrant-serial#1]
Console Output:

sh-3.2# vagrant up
Failed to load the "vagrant-serial" plugin. View logs for more details.

Bringing machine 'precisehost' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
- Unknown configuration section 'serial'.

sh-3.2# 

Vagrantfile:

Vagrant.configure("2") do |config|

config.vm.define :precisehost do |precise_config|

```
    precise_config.serial.forward_com1 = 1024
    precise_config.ssh.forward_x11 = "true"
    precise_config.vm.box = "arduino"
    precise_config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    precise_config.vm.hostname = "arduino.plot.dev"
    #precise_config.vm.network :private_network, ip: "192.168.1.12"
    precise_config.vm.network :public_network
    precise_config.vm.synced_folder "manifests", "/etc/puppet/manifests"
    precise_config.vm.synced_folder "modules", "/etc/puppet/modules"
    precise_config.vm.synced_folder "ArduinoPlot", "/home/ArduinoPlot"
    precise_config.vm.synced_folder "PythonDev", "/home/PythonDev"
    precise_config.vm.provision :shell, :path => "puppet_master.sh"
    precise_config.vm.provision :puppet, :module_path => "modules", :manifests_path => "manifests", :manifest_file => "boot_arduino.pp"
    end
```

end

**Comment by malnick** [comment]
Also:

sh-3.2# vagrant plugin list
vagrant-serial (1.0.3)
vagrant-vbguest (0.8.0)
sh-3.2#

**Comment by malnick** [comment]
sh-3.2# cat vagrantlog.txt | grep serial
 INFO environment: Loading plugin from JSON: vagrant-serial
ERROR root: Failed to load plugin: vagrant-serial
ERROR root: /var/root/.vagrant.d/gems/gems/vagrant-serial-1.0.3/lib/vagrant-serial/config.rb:3:in `<module:Serial>'
/var/root/.vagrant.d/gems/gems/vagrant-serial-1.0.3/lib/vagrant-serial/config.rb:2:in`module:Vagrant'
/var/root/.vagrant.d/gems/gems/vagrant-serial-1.0.3/lib/vagrant-serial/config.rb:1:in `<top (required)>'
/var/root/.vagrant.d/gems/gems/vagrant-serial-1.0.3/lib/vagrant-serial.rb:2:in`<top (required)>'
 INFO interface: error: Failed to load the "vagrant-serial" plugin. View logs for more details.
Failed to load the "vagrant-serial" plugin. View logs for more details.
- Unknown configuration section 'serial'.
- Unknown configuration section 'serial'.
- Unknown configuration section 'serial'.
- Unknown configuration section 'serial'.
- Unknown configuration section 'serial'.
  sh-3.2#
